Repository nasa-gibs/worldview-components, pull requests merged in 2018-07, with the labels that each got.

#64 Properly set state within componentWillReceiveProps
  src/scripts/components/layer/row.js
Labels: ready for review

#63 Fix product picker info buttons expand multiple layers at once
  src/scripts/components/layer/list.js
Labels: ready for review

#65 When KMZ is selected, disable worldfile select (and default to 'No')
  src/scripts/components/image-panel/select.js
Labels: ready for review

#62 Prevent start dragger from dragging both draggers off the timeline into the 'future'
  src/scripts/components/range-selection/range-selection.js
Labels: bug, ready for review

#66 Adjust yearly layer date range
  src/scripts/components/layer/row.js
Labels: under development

#67 v1.9.0
  package-lock.json
  package.json
Labels: under development
